services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://api:8080}
    networks:
      - api
    ports:
      - "${FRONTEND_PORT:-3000}:80"

networks:
  api:
    external: true
    name: backend_default
