FROM python:3.13

WORKDIR /utils

COPY ../utils/requirements.txt .

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install -r requirements.txt

COPY ../utils/* .

CMD ["python", "gen_data.py"]
