@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

object Самолеты {
   идентификатор
   идентификатор модели самолета
   регистрационный номер
   серийный номер
   пройденное расстояние
}
object "Модели самолетов" {
   идентификатор
   производитель
   название
   масса
   максимальная высота
   максимальная скорость
}
object Страны {
    идентификатор
    код
    название
}
object Города {
    идентификатор
    идентификатор страны
    название
}
object Аэропорты {
   идентификатор
   идентификатор города
   IATA код
   название
}
object Маршруты {
   идентификатор
   идентификатор рейса
   выход на посадку аэропорта вылета
   выход на посадку аэропорта прибытия
}
object Рейсы {
   идентификатор
   идентификатор самолета
   запланированный вылет
   запланированное прибытие
   время вылета
   время прибытия
   статус
   план
}
object "Выходы на посадку" {
   идентификатор
   идентификатор аэропорта
   номер
}
object Уведомления {
   идентификатор
   дата создания
   дата отправки
   сообщение
   статус
   тип
}
object Подписки {
   идентификатор
   идентификатор пользователя
   идентификатор рейса
}
object Пользователи {
   идентификатор
   адрес электронной почты
   пароль
   роль
}

Самолеты         -[#595959,plain]-^  "Модели самолетов" : "идентификатор модели самолета:идентификатор"
Маршруты    -[#595959,plain]-^  Рейсы         : "идентификатор рейса:идентификатор"
Маршруты    -[#595959,plain]-^  "Выходы на посадку"           : "выход на посадку аэропорта вылета:идентификатор"
Маршруты    -[#595959,plain]-^  "Выходы на посадку"           : "выход на посадку аэропорта прибытия:идентификатор"
Рейсы          -[#595959,plain]-^  Самолеты        : "идентификатор самолета:идентификатор"
"Выходы на посадку"            -[#595959,plain]-^  Аэропорты        : "идентификатор аэропорта:идентификатор"
Подписки    -[#595959,plain]-^  Рейсы         : "идентификатор рейса:идентификатор"
Подписки    -[#595959,plain]-^  Пользователи           : "идентификатор пользователя:идентификатор"
Аэропорты    -[#595959,plain]-^  Города           : "идентификатор города:идентификатор"
Города    -[#595959,plain]-^  Страны           : "идентификатор страны:идентификатор"
@enduml
