services:
  data_generator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: airline_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared_postgres
