services:
  data_generator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: airline_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      - shared

  migrate_pg_to_mysql:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "migrate_pg_to_mysql.py"]
    environment:
      POSTGRES_DB: airline_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MYSQL_DATABASE: airline_tracker
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pswd
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    depends_on:
      data_generator:
        condition: service_completed_successfully
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared_postgres
