-- create or replace function add_flight(
--     p_flight_id uuid,
--     p_scheduled_departure timestamp,
--     p_scheduled_arrival timestamp,
--     p_flight_status varchar,
--     p_flight_plan varchar,
--     p_aircraft_id uuid,
--     p_departure_airport_id uuid,
--     p_arrival_airport_id uuid,
--     p_departure_gate_id uuid,
--     p_arrival_gate_id uuid
-- )
--     returns void
--     language plpgsql
-- as $$ begin
--     if p_scheduled_arrival <= p_scheduled_departure then
--         raise exception 'can not land before departing';
--     end if;
--
--     if not exists(select 1 from aircraft where id = p_aircraft_id) then
--         raise exception 'aircraft does not exist';
--     end if;
--
--     if p_departure_airport_id = p_arrival_airport_id then
--         raise exception 'airports must be different';
--     end if;
--
--     if not exists(select 1 from airports where id = p_departure_airport_id) then
--         raise exception 'departure airport does not exist';
--     end if;
--
--     if not exists(select 1 from airports where id = p_arrival_airport_id) then
--         raise exception 'arrival airport does not exist';
--     end if;
--
--     if not exists(select 1 from gates where id = p_departure_gate_id and airport_id = p_departure_airport_id) then
--         raise exception 'departure gate does not exist';
--     end if;
--
--     if not exists(select 1 from gates where id = p_arrival_gate_id and airport_id = p_arrival_airport_id) then
--         raise exception 'arrival gate does not exist';
--     end if;
--
--     insert into flights (id,
--                          aircraft_id,
--                          scheduled_departure,
--                          scheduled_arrival,
--                          status,
--                          plan)
--     values (p_flight_id,
--             p_aircraft_id,
--             p_scheduled_departure,
--             p_scheduled_arrival,
--             p_flight_status,
--             p_flight_plan);
--
--     insert into flight_routes (flight_id, departure_gate_id, arrival_gate_id)
--     values (p_flight_id, p_departure_gate_id, p_arrival_gate_id);
-- end; $$;
--
-- create or replace function scan_flight_info(
--     p_flight_id uuid
-- )
--     returns
--         table
--         (
--             id                   uuid,
--             aircraft_id          uuid,
--             scheduled_departure  timestamp,
--             scheduled_arrival    timestamp,
--             actual_departure     timestamp,
--             actual_arrival       timestamp,
--             status               varchar(20),
--             plan                 varchar(128),
--             departure_gate_id    uuid,
--             arrival_gate_id      uuid,
--             departure_airport_id uuid,
--             arrival_airport_id   uuid
--         )
--     language plpgsql
-- as
-- $$
-- begin
--     return query
--         select f.id,
--                f.aircraft_id,
--                f.scheduled_departure,
--                f.scheduled_arrival,
--                f.actual_departure,
--                f.actual_arrival,
--                f.status,
--                f.plan,
--                fr.departure_gate_id,
--                fr.arrival_gate_id,
--                gd.airport_id,
--                ga.airport_id
--         from flights f
--                  join flight_routes fr on f.id = fr.flight_id
--                  join gates gd on gd.id = fr.departure_gate_id
--                  join gates ga on ga.id = fr.arrival_gate_id
--         where f.id = p_flight_id;
-- end;
-- $$;
--
-- create or replace function scan_flights_info()
--     returns
--         table
--         (
--             id                   uuid,
--             aircraft_id          uuid,
--             scheduled_departure  timestamp,
--             scheduled_arrival    timestamp,
--             actual_departure     timestamp,
--             actual_arrival       timestamp,
--             status               varchar(20),
--             plan                 varchar(128),
--             departure_gate_id    uuid,
--             arrival_gate_id      uuid,
--             departure_airport_id uuid,
--             arrival_airport_id   uuid
--         )
--     language plpgsql
-- as
-- $$
-- begin
--     return query
--         select f.id,
--                f.aircraft_id,
--                f.scheduled_departure,
--                f.scheduled_arrival,
--                f.actual_departure,
--                f.actual_arrival,
--                f.status,
--                f.plan,
--                v.departure_gate_id,
--                v.arrival_gate_id,
--                gd.airport_id,
--                ga.airport_id
--         from flights f
--                  join flight_routes v on f.id = v.flight_id
--                  join gates gd on gd.id = v.departure_gate_id
--                  join gates ga on ga.id = v.arrival_gate_id;
-- end;
-- $$;
--
-- create or replace function subscribe(p_uid uuid, p_fid uuid)
--     returns void language plpgsql
-- as
-- $$
-- begin
--     if not exists(select 1 from users where id = p_uid) then
--         raise exception 'user not found' using errcode = 'P0002';
--     end if;
--
--     if not exists(select 1 from flights where id = p_fid) then
--         raise exception 'flight not found' using errcode = 'P0002';
--     end if;
--
--     insert into subscriptions(user_id, flight_id)
--     values (p_uid, p_fid);
-- end;
-- $$;
--
-- create or replace function scan_user_flights_info(p_uid uuid)
--     returns
--         table
--         (
--             id                   uuid,
--             aircraft_id          uuid,
--             scheduled_departure  timestamp,
--             scheduled_arrival    timestamp,
--             actual_departure     timestamp,
--             actual_arrival       timestamp,
--             status               varchar(20),
--             plan                 varchar(128),
--             departure_gate_id    uuid,
--             arrival_gate_id      uuid,
--             departure_airport_id uuid,
--             arrival_airport_id   uuid
--         )
--     language plpgsql
-- as
-- $$
-- begin
--     if not exists(select 1 from users u where u.id = p_uid) then
--         raise exception 'user not found' using errcode = 'P0002';
--     end if;
--
--     return query
--         select f.id,
--                f.aircraft_id,
--                f.scheduled_departure,
--                f.scheduled_arrival,
--                f.actual_departure,
--                f.actual_arrival,
--                f.status,
--                f.plan,
--                v.departure_gate_id,
--                v.arrival_gate_id,
--                gd.airport_id,
--                ga.airport_id
--         from flights f
--                  join flight_routes v on f.id = v.flight_id
--                  join gates gd on gd.id = v.departure_gate_id
--                  join gates ga on ga.id = v.arrival_gate_id
--                  join subscriptions s on s.flight_id = f.id and s.user_id = p_uid;
-- end;
-- $$;